on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker://marpteam/marp-cli:latest
        with:
          args: -I . -O dist
          user: root
      - uses: docker://marpteam/marp-cli:latest
        with:
          args: -I . -O dist --pdf
          user: root
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - id: deployment
        uses: actions/deploy-pages@v4
